version: '3.9'

services:
  mysql:
    image: mysql:8.0.32
    container_name: mysql
    restart: always
    hostname: mysql
    command: --default-authentication-plugin=mysql_native_password
    shm_size: 256m
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: tacocloud
      MYSQL_PASSWORD: 123456
      LANG=: en_US.UTF-8
    networks:
      - community-network
    ports:
      - "18989:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ${MYSQL_DATA}:/var/lib/mysql
    healthcheck:
      test: [ "CMD","mysqladmin","ping","-h","localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s

  zookeeper:
    image: zookeeper:3.9.1
    container_name: zookeeper
    ports:
      - "32180:2180"
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
#    expose:
#      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    ports:
      - "19000:9000"
    environment:
      - KAFKA_BROKERCONNECT=kafka:9093

networks:
  community-network:
    name: community-network
    driver: bridge